services:
  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: edge-npm
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - "${DOCKER_DIR}/npm/data:/data"
      - "${DOCKER_DIR}/letsencrypt:/etc/letsencrypt"
    networks:
      - npm-edge

  adguardhome:
    image: adguard/adguardhome
    container_name: edge-agh
    restart: unless-stopped
    network_mode: host
    volumes:
      - "${DOCKER_DIR}/adguard/work:/opt/adguardhome/work"
      - "${DOCKER_DIR}/adguard/conf:/opt/adguardhome/conf"

  # crowdsec:
  #   image: crowdsecurity/crowdsec
  #   container_name: edge-crowdsec
  #   restart: always
  #   environment:
  #     COLLECTIONS=${CROWDSEC_EDGE_LIST}
  #     GID=${CROWDSEC_GID:-1000}
  #     TZ=${TZ:-America/Chicago}
  #     DISABLE_LOCAL_API=true
  #     LOCAL_API_URL=${CROWDSEC_LAPI}
  #     AGENT_USERNAME=${HOSTNAME}
  #     AGENT_PASSWORD=${CROWDSEC_MACHINE_PASS}
  #   volumes:
  #     - "${DOCKER_DIR}/crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml"
  #     - "${DOCKER_DIR}/crowdsec/logs:/var/log/nginx"
  #     - "${DOCKER_DIR}/crowdsec/crowdsec-db:/var/lib/crowdsec/data/"
  #     - "${DOCKER_DIR}/crowdsec/crowdsec-config:/etc/crowdsec/"
  #
  # crowdsec-bouncer:
  #   image: crowdsecurity/crowdsec-firewall-bouncer:latest
  #   container_name: edge-cs-bouncer
  #   network_mode: host
  #   cap_add:
  #     - NET_ADMIN
  #     - NET_RAW
  #   environment:
  #     - DISABLE_IPV6=true
  #     - API_URL=${LAPI_URL}
  #     - API_KEY=${CROWDSEC_BOUNCER_KEY}
  #   restart: unless-stopped
  #   depends_on:
  #     - crowdsec
  #
networks:
  npm-edge:
    external: true
    name: npm-edge

      
