services:
  dockge:
    image: louislam/dockge:latest
    container_name: core-dockge
    restart: unless-stopped
    ports:
      - "5001:5001"
    networks:
      - proxy-core
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_DIR}/dockge:/app/data
      - /opt/stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks

networks:
  proxy-core:
    external: true
    name: proxy-core
