- name: Ensure backup job exists
  community.proxmox.proxmox_backup:
    storage: prod-backups-01
    mode: all
    compress: zstd
    compression_threads: 4
    bandwith: 75
    comment: {% raw %}{{ guestname }},{{ vmid }}{% endraw %}
    retention: keep-last=3, keep-daily=7, keep-monthly=2, keep-weekly=4
    notification_mode: notification-system
    state: present
    enable: true

- name: Ensure VMs present in backup job
  community.proxmox.proxmox_backup_schedule:
    vm_name: "{{ item }}"
    backup_id: 'backup-8ad9d161-67d8'
    state: present
  loop: "{{ groups['vm_nodes'] | default([]) }}"

- name: Ensure LXCs present in backup job
  community.proxmox.proxmox_backup_schedule:
    vm_name: "{{ item }}"
    backup_id: 'backup-8ad9d161-67d8'
    state: present
  loop: "{{ groups['lxc_nodes'] | default([]) }}"

