- name: List existing metric servers
  check_mode: false
  ansible.builtin.command:
    cmd: pvesh get /cluster/metrics/server --output-format json
  register: metric_servers_raw
  changed_when: false

- name: Check if OTEL metric server exists
  ansible.builtin.set_fact:
    otel_metric_server_exists: >-
      {{ (metric_servers_raw.stdout | default ('[]') | from_json | selectattr('id', 'equalto', 'ops-itim-01') | list | length > 0 }}

- name: Create OTEL metric server
  when: not otel_metric_server_exists
  ansible.builtin.command:
    cmd: >-
      pvesh create /cluster/metrics/server/ops-itim-01
      --type opentelemetry
      --server {{ ops_itim_01_ip }}
      --port 4318
      --otel-protocol http
      --otel-path /v1/metrics
      --otel-verify-ssl 0
      --enabled 1
      --otel-timeout 5
      --otel-compression gzip
      --otel-max-body-size 10000000
