- name: Create Local ZFS Pool
  community.proxmox.proxmox_storage:
    name: Dual1T_ZFS
    type: "zfspool"
    content: "images,rootdir"
    state: present
    enable: true

- name: Mount prod-backups-01
  community.proxmox.proxmox_storage:
    storage: "prod-backups-01"
    type: "nfs"
    server: "{{ motherbase_storage_ip }}"
    export: "/mnt/kazuhira/proxmox_backups"
    content: "backup"
    state: "present"
    enable: "true"

- name: Mount prod-disks-01
  community.proxmox.proxmox_storage:
    storage: "prod-disks-01"
    type: "nfs"
    server: "{{ motherbase_storage_ip }}"
    export: "/mnt/kazuhira/proxmox_disks"
    content: "images,rootdir"
    state: "present"
    enable: "true"

- name: Mount prod-imgs-01
  community.proxmox.proxmox_storage:
    storage: "prod-imgs-01"
    type: "nfs"
    server: "{{ motherbase_storage_ip }}"
    export: "/mnt/kazuhira/proxmox_isos"
    content: "vztmpl,iso"
    state: "present"
    enable: "true"
