- name: Create Local ZFS Pool
  community.proxmox.proxmox_storage:
    name: Dual1T_ZFS
    zfspool_options: 
      pool: Dual1T_ZFS
      sparse: false
    type: "zfspool"
    content: ["images", "rootdir"]
    state: present

- name: Mount prod-backups-01
  community.proxmox.proxmox_storage:
    name: prod-backups-01
    type: "nfs"
    nfs_options:
      server: "{{ motherbase_storage_ip }}"
      export: "/mnt/kazuhira/proxmox_backups"
    content: ["backup"]
    state: "present"

- name: Mount prod-disks-01
  community.proxmox.proxmox_storage:
    name: prod-disks-01
    type: "nfs"
    nfs_options:
      server: "{{ motherbase_storage_ip }}"
      export: "/mnt/kazuhira/proxmox_disks"
    content: ["images", "rootdir"]
    state: "present"

- name: Mount prod-imgs-01
  community.proxmox.proxmox_storage:
    name: prod-imgs-01
    type: "nfs"
    nfs_options:
      server: "{{ motherbase_storage_ip }}"
      export: "/mnt/kazuhira/proxmox_isos"
    content: ["vztmpl", "iso"]
    state: "present"
