- name: Reload nftables
  ansible.builtin.service:
    name: nftables
    state: reloaded
  notify:
    - Restart Docker

- name: Restart Docker
  ansible.builtin.service:
    name: docker
    state: reloaded
