all:
  children:
    lxc_nodes:
      vars:
        ansible_user: root
        ansible_python_interpreter: auto_silent
        ansible_ssh_private_key_file: ~/.ssh/ansible-manager
      hosts:
        ops-core-01:
          ansible_host: 10.20.0.50
        ops-itim-01:
          ansible_host: 10.20.0.51
        data-imgs-01:
          ansible_host: 10.30.0.80
    vm_nodes:
      vars:
        ansible_become: true
        ansible_user: t
        ansible_become_user: root
        ansible_become_method: su
        ansible_python_interpreter: auto_silent
        ansible_ssh_private_key_file: ~/.ssh/ansible-manager
      hosts:
        edge-srv-01:
          ansible_host: 10.40.0.50
          ansible_port: 2222
          ansible_become_pass: "{{ vault_edge_srv_01_sudo_pass }}"
        media-proc-01:
          ansible_host: 10.30.0.50
          ansible_become_pass: "{{ vault_media_proc_01_sudo_pass }}"
    infra_nodes:
      hosts:
        raiden:
          ansible_host: 10.20.0.11
        motherbase:
          ansible_host: 10.20.0.10

    crowdsec_agents:
      hosts:
        edge-srv-01:

    prom_endpoint:
      hosts:
        edge-srv-01:
        media-proc-01:
        data-imgs-01:
        ops-itim-01:

    docker_nodes:
      hosts:
        ops-core-01:
        media-proc-01:
        data-imgs-01:
        edge-srv-01:

    alloy_bare:
      hosts:
        ops-itim-01:
