all:
  children:
    vars:
    lxc_nodes:
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/ansible-manager
        ansible_python_interpreter: auto_silent
        node_type: lxc
      hosts:
        ops-core-01:
          ansible_host: 10.20.0.50
          labels: [docker, management]
        ops-itim-01:
          ansible_host: 10.20.0.51
          labels: [management]
        data-imgs-01:
          ansible_host: 10.30.0.80
          labels: [docker, media, trusted]
        data-fin-01:
          ansible_host: 10.30.0.60
          labels: [trusted]
        data-sync-01:
          ansible_host: 10.30.0.70
          labels: [trusted]
    vm_nodes:
      vars:
        ansible_become: true
        ansible_user: t
        ansible_become_user: root
        ansible_become_method: su
        ansible_ssh_private_key_file: ~/.ssh/ansible-manager
        ansible_python_interpreter: auto_silent
        node_type: vm
      hosts:
        edge-srv-01:
          ansible_host: 10.40.0.50
          ansible_port: 2222
          ansible_become_pass: "{{ vault_edge_srv_01_sudo_pass }}"
          labels: [docker, edge]
        media-proc-01:
          ansible_host: 10.30.0.50
          ansible_become_pass: "{{ vault_media_proc_01_sudo_pass }}"
          labels: [docker, media, trusted]
    infra_nodes:
      hosts:
        raiden:
          ansible_host: 10.20.0.11
          ansible_user: root
          ansible_pass: "{{ vault_ansible_pve_pass }}"
          ansible_ssh_private_key_file: ~/.ssh/ansible-manager          
          node: raiden
          api_host: 10.20.0.11
          api_user: root@pam
          storage_ip: 10.50.0.2
          api_token_id: "{{ vault_ansible_test_id }}"
          api_token_secret: "{{ vault_ansible_test_secret }}"
          labels: [proxmox, compute, infra, management]
        motherbase:
          ansible_host: 10.20.0.10
          ansible_connection: local # run locally and target the API
          truenas_api_key: "{{ vault_truenas_api_key }}"
          truenas_validate_certs: false
          labels: [truenas, storage, infra, management]
    ufi_cluster:
      hosts:
        ufi-ucg-m:
          ansible_host: 10.20.0.1
          ansible_connection: local
          unifi_api_user: "{{ vault_unifi_user }}"
          unifi_api_pass: "{{ vault_unifi_pass }}"
          labels: [unifi, network, infra, management]

    crowdsec_agents:
      hosts:
        edge-srv-01:

    prom_endpoint:
      hosts:
        edge-srv-01:
        media-proc-01:
        data-imgs-01:
        ops-itim-01:

    docker_nodes:
      hosts:
        ops-core-01:
        media-proc-01:
        data-imgs-01:
        edge-srv-01:

    alloy_bare:
      hosts:
        ops-itim-01:

    vlan_mgmt:
      vars:
        gateway_ip: 10.20.0.1
      hosts:
        raiden:
        motherbase:
        ufi-ucg-m:
        ops-core-01:
        ops-itim-01:

    vlan_trusted:
      vars:
        gateway_ip: 10.30.0.1
      hosts:
        media-proc-01:
        data-sync-01:
        data-imgs-01:
        data-fin-01:

    vlan_dmz:
      vars:
        gateway_ip: 10.40.0.1
      hosts:
        edge-srv-01:

    core_proxy:
      hosts:
        ops-core-01:
    edge_proxy:
      hosts:
        edge-srv-01:

    debian:
      hosts:
        media-proc-01:
        data-sync-01:
        data-imgs-01:
        data-fin-01:
        ops-core-01:
        ops-itim-01:
        edge-srv-01:
