- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Ensure keyrings and prereqs installed
  ansible.builtin.apt:
    pkg:
      - debian-archive-keyring
      - gnupg
      - apt-transport-https
    state: present
    update_cache: true
  become: true

- name: Download Crowdsec GPG Key
  ansible.builtin.get_url:
    url: https://packagecloud.io/crowdsec/crowdsec/gpgkey
    dest: /tmp/crowdsec_repo.asc
    mode: '0644'
  become: true
  register: crowdsec_key

- name: Dearmor Crowdsec GPG Key
  ansible.builtin.command:
    cmd: gpg --dearmor -o /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg /tmp/crowdsec_repo.asc
    creates: /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg
  become: true
  when: crowdsec_key.changed

- name: Cleanup temp GPG key
  ansible.builtin.file:
    path: /tmp/crowdsec_repo.asc
    state: absent
  become: true
  when: crowdsec_key.changed

- name: Add Crowdsec Repository
  ansible.builtin.deb822_repository:
    name: crowdsec
    types: deb
    uris: https://packagecloud.io/crowdsec/crowdsec/debian/
    suites: bookworm
    components: main
    signed_by: /etc/apt/keyrings/crowdsec_crowdsec-archive-keyring.gpg
  become: true
  register: crowdsec_repo

- name: Force apt cache update for new repo
  ansible.builtin.apt:
    update_cache: true
  become: true
  when: (crowdsec_key.changed or crowdsec_repo.changed) and not ansible_check_mode

- name: Install CrowdSec Security Engine
  ansible.builtin.apt:
    pkg:
      - crowdsec
      - crowdsec-firewall-bouncer
    state: present
    update_cache: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"
  notify: Restart Crowdsec

- name: Install Collections
  ansible.builtin.command: "cscli collections install {{ item }}"
  become: true
  loop:
    - crowdsecurity/nginx
    - crowdsecurity/nginx-proxy-manager
    - crowdsecurity/base-http-scenarios
    - crowdsecurity/linux
    - crowdsecurity/appsec-virtual-patching
    - crowdsecurity/appsec-generic-rules
    - crowdsecurity/appsec-crs
  register: collection_install
  changed_when: "'msg=\"collection installed\"' in collection_install.stdout or 'installed' in collection_install.stdout"
  notify: Restart Crowdsec

- name: Ensure Crowdsec service is enabled and running
  ansible.builtin.systemd_service:
    name: crowdsec
    state: started
    enabled: true
  become: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: Ensure Crowdsec acquis dir exists
  ansible.builtin.file:
    path: /etc/crowdsec/acquis.d
    state: directory
    mode: '0755'
  become: true

- name: Configure NPM log acquis
  ansible.builtin.template:
    src: acquis_npm.yaml.j2
    dest: /etc/crowdsec/acquis.d/nginx-proxy-manager.yaml
    mode: '0644'
  become: true
  notify: Restart Crowdsec

- name: Ensure Crowdsec config exists
  ansible.builtin.file:
    path: /etc/crowdsec/config.yaml
    state: file
  become: true

- name: Populate Crowdec local config overrides
  ansible.builtin.template:
    src: config.yaml.local.j2
    dest: /etc/crowdsec/config.yaml.local
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Crowdsec

- name: Ensure LAPI config exists
  ansible.builtin.file:
    path: /etc/crowdsec/local_api_credentials.yaml
    state: file
  become: true

- name: Deploy LAPI connection creds
  ansible.builtin.template:
    src: local_api_credentials.yaml.j2
    dest: /etc/crowdsec/local_api_credentials.yaml
    owner: root
    group: root
    mode: '0600'
  become: true
  notify: Restart Crowdsec

- name: Validate Crowdsec config syntax
  ansible.builtin.command: crowdsec -t
  become: true
  changed_when: false
  when: not ansible_check_mode

- name: Configure NPM
  ansible.builtin.include_tasks: configure_npm.yml
