services:
  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    restart: unless-stopped
    user: "0:0"
    privileged: true
    ports:
      - "12345:12345"
      - "1514:1514/udp"
      - "1514:1514/tcp"
    volumes:
      # Config
      - ${DOCKER_DIR}/alloy/config.alloy:/etc/alloy/config.alloy:ro

      # Docker & Container Management
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /run/containerd/containerd.sock:/run/containerd/containerd.sock:ro

      # System Logging & Identity
      - /var/log/journal:/var/log/journal:ro
      - /run/log/journal:/run/log/journal:ro
      - /etc/machine-id:/etc/machine-id:ro

      # Host Metrics, Storage, & Cgroups
      - /:/host:ro
      - /:/rootfs:ro
      - /sys:/sys:ro
      - /dev/disk/:/dev/disk:ro
    command: run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy
