services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: access-vaultwarden
    restart: always
    environment:
      - ADMIN_TOKEN=${ADMIN_TOKEN}
      - WEBSOCKET_ENABLED=true
      - SIGNUPS_ALLOWED=true
      - DOMAIN=${DOMAIN}
    volumes:
      - ${DOCKER_DIR}/vaultwarden/vw-data:/data
    ports:
      - "9445:80"
    networks:
      - proxy-core

networks:
  proxy-core:
    external: true
    name: proxy-core
