services:
  adguardhome:
    image: adguard/adguardhome
    container_name: core-agh
    restart: unless-stopped
    network_mode: host
    volumes:
      - ${DOCKER_DIR}/adguard/work:/opt/adguardhome/work
      - ${DOCKER_DIR}/adguard/conf:/opt/adguardhome/conf

  caddy:
    image: serfriz/caddy-cloudflare:latest
    container_name: core-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - CLOUDFLARE_API_TOKEN=${CF_TOKEN}
    volumes:
      - ${DOCKER_DIR}/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - ${DOCKER_DIR}/caddy/data:/data
      - ${DOCKER_DIR}/caddy/config:/config
    networks:
      - proxy-core

networks:
  proxy-core:
    driver: bridge
    name: proxy-core

