- name: Configure Docker Alloy Containers
  ansible.builtin.include_tasks: docker.yml
  when: inventory_hostname in groups['docker_nodes']

- name: Configure Bare Alloy Instances
  ansible.builtin.include_tasks: bare.yml
  when: inventory_hostname in groups['alloy_bare']
