- name: Ensure Grafana Alloy directory exists
  ansible.builtin.file:
    path: "/opt/docker-data/alloy"
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: Render and deploy alloy.config
  ansible.builtin.template:
    src: config.alloy.j2
    dest: "/opt/docker-data/alloy/config.alloy"
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: Restart Alloy Container
